config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'

  resources :lists, only: [:show, :create, :update, :destroy]
  post '/share_list/:id', to: 'lists#share', as: 'share_list'
  get 'my_lists', to: 'lists#index'

  resources :songs, only: [:update, :create, :destroy]
  post 'collect_click', to: 'songs_statistic#collect', format: :js

  namespace :api, defaults: {format: :json} do
    devise_for :users
    resources :songs, only: [:update, :create, :destroy]
    resources :lists, only: [:index, :show, :create, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end

end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TestProject
    = csrf_meta_tags
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
    = yield :stylesheets
  body
    .container
      nav.navbar.navbar-default
        .container-fluid
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'logo.png', class: 'logo-image', alt: 'Logo'

          ul.nav.navbar-nav
            - if user_signed_in?
              li
                = link_to t(:my_lists), my_lists_path
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                = link_to t(:log_out), destroy_user_session_path, method: :delete
            - else
              li
                = link_to t(:log_in), new_user_session_path
              li
                = link_to t(:register), new_user_registration_path
      .container#messages
        - flash.each do |key, value|
          div class=("alert alert-#{key}")
            button.close.close-sm
              i.fa.fa-times
            = value.html_safe
      = yield
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = yield :plugins